default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['GRANTZILLA_DATABASE_USERNAME'] %>
  password: <%= ENV['GRANTZILLA_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: grantzilla_development

test:
  <<: *default
  database: grantzilla_test

production:
  <<: *default
  database: grantzilla_production
